### ISSUE TITLE
it seem like the npm package is not the newest version.

### ISSUE THREAD

**Issue by xiwc** [websanova/node-url#1]
when url like: http://localhost:9000/#/home?debug=all
wurl('?debug') is undefined.

if url write like: http://localhost:9000?debug=all/#/home
wurl('?debug')  work fine.

**Comment by websanova** [comment]
Yes, because you have a hashtag. You will have to parse the hash first and
then the debug if you want to do it that way.

**Comment by xiwc** [comment]
but, js-url@1.8.8 work fine.
![image](https://cloud.githubusercontent.com/assets/8816203/17084166/bec28e7c-51e9-11e6-9445-c91ea02d95c8.png)

**Comment by websanova** [comment]
Try this:

var hash = url('hash', u);
var debug = url('?debug'), hash);

**Comment by xiwc** [comment]
OK, i will try, 3ks!

**Comment by xiwc** [comment]
Now, i have wrap a method to use your lib like this:

```
            /**
             * 获取url中的查询参数值
             * @param  {[type]} name 查询参数名称
             * @return {[type]}      查询参数值
             */
            urlQuery: (name) => {
                return wurl('?' + name) || wurl('?' + name, wurl('hash'));
            }
```

I don't think it's an elegant way to use it. I prefer use like `wurl('?name')` in js-url@1.8.8

Isn't it a issue bug? Will you fix this problem?

**Comment by websanova** [comment]
Updated.
